server_connect_timeout: 5000
listeners:
- query_port: 25565
  motd: '&6ChaosOlymp Test Server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
  priorities:
  - server1
  - server2
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
  forced_hosts:
    pvp.md-5.net: pvp
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - portals.check
  - portals.create
  - portals.debug
  - portals.info
  - portals.link
  - portals.list
  - portals.list.all
  - portals.list.public
  - portals.modify
  - portals.remove
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: c25c5edc-60ea-4d54-b4ff-cc042233d6c8
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  server1:
    motd: '&3Test Server 1'
    address: localhost:25566
    restricted: false
  server2:
    motd: '&3Test Server 2'
    address: localhost:25567
    restricted: false
